# =============================================================================
# Qdrant Vector Database Configuration
# =============================================================================
# This configuration file sets up Qdrant for the Org Archivist application.
# Simplified configuration for compatibility with latest Qdrant versions.
# =============================================================================

service:
  # HTTP API endpoint
  http_port: 6333

  # gRPC API endpoint (faster for bulk operations)
  grpc_port: 6334

  # Enable CORS for web-based clients
  enable_cors: true

  # Maximum request size (in bytes) - 100MB
  max_request_size_mb: 100

storage:
  # Storage backend: 'disk' for persistent storage
  storage_path: /qdrant/storage

# Telemetry (disable for privacy)
telemetry_disabled: true

# Logging level
log_level: INFO
